name: pocketid-deploy
services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:latest
    restart: unless-stopped
    env_file: .env
    volumes:
      - "./data:/app/backend/data"
    # Optional healthcheck
    healthcheck:
      test: "curl -f http://localhost/health"
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s