---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy-pv-claim
  labels:
    app: ntfy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy-pv-user-claim
  labels:
    app: ntfy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: caddy-data-pv-claim
  labels:
    app: ntfy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: caddy-config-pv-claim
  labels:
    app: ntfy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: ntfy
spec:
  containers:
  - name: ntfy
    image: docker.io/binwiederhier/ntfy:latest
    args: ["serve"]
    env:
    - name: TZ
      value: America/Toronto
    volumeMounts:
    - name: ntfy-cache
      mountPath: /var/cache/ntfy
    - name: ntfy-auth
      mountPath: /var/lib/ntfy
    - name: ntfy-config
      mountPath: /etc/ntfy
  - name: caddy
    image: docker.io/library/caddy:latest
    volumeMounts:
    - name: caddy-config
      mountPath: /etc/caddy
      #subPath: CaddyFile
    - name: caddy-data
      mountPath: /data
    - name: caddy-configs
      mountPath: /config
  volumes:
  - name: ntfy-cache
    persistentVolumeClaim:
      claimName: ntfy-pv-claim
  - name: ntfy-auth
    persistentVolumeClaim:
      claimName: ntfy-pv-user-claim
  - name: ntfy-config
    configMap:
      name: ntfy-config
  - name: caddy-config
    configMap:
      name: caddy-config
  - name: caddy-data
    persistentVolumeClaim:
      claimName: caddy-data-pv-claim
  - name: caddy-configs
    persistentVolumeClaim:
      claimName: caddy-config-pv-claim