---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ntfy-config
data:
  GF_PATHS_PROVISIONING: /etc/grafana/provisioning
  GF_AUTH_ANONYMOUS_ENABLED: false
  GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
  GF_SERVER_ROOT_URL: https://grafana.example.com
  GF_AUTH_GENERIC_OAUTH_ENABLED: true
  GF_AUTH_GENERIC_OAUTH_NAME: ssoprovider
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: myclientid
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: myclientsecret
  GF_AUTH_GENERIC_OAUTH_SCOPES: openid profile email
  GF_AUTH_GENERIC_OAUTH_AUTH_URL: authurl
  GF_AUTH_GENERIC_OAUTH_TOKEN_URL: authtoken
  GF_AUTH_GENERIC_OAUTH_API_URL: authapiurl
  GF_AUTH_SIGNOUT_REDIRECT_URL: authredirect
  GF_AUTH_OAUTH_AUTO_LOGIN: true
  GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: contains(groups, 'GrafanaAdmins') && 'Admin' || contains(groups, 'GrafanaEditors') && 'Editor' || 'Viewer'